include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    sort_pub_dependencies: ignore
    always_specify_types: ignore

linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false