name: drbob
description: A companion app for AA members.

version: 20.04.30+2196

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # intl
  flutter_localizations:
    sdk: flutter 
  intl: ^0.19.0
  slang: ^3.31.1
  slang_flutter: ^3.31.0

  # state
  provider: ^6.0.5
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

  # var
  flutter_local_notifications: ^17.2.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

  # util
  timezone: ^0.9.4

  # widgets
  gauge_indicator: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # analysis
  analyzer: ^5.3.0
  flutter_lints: ^2.0.3
  custom_lint: ^0.5.3
  
  # tests
  test: ^1.5.1

  # runner
  build_runner: ^2.4.6
  slang_build_runner: ^3.23.0
  riverpod_generator: ^2.3.2

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    # - assets/

    - assets/i18n/

    - assets/daily_reflections/

    - assets/big_book/

    - assets/images/doc.png